file:
  /docker-entrypoint.bash:
    exists: true
    owner: root
    group: root
    filetype: file
    contains: []
  /usr/local/tomcat/webapps:
    exists: true
    mode: "0750"
    owner: tomcat
    group: tomcat
    filetype: directory
    contains: []
  /usr/local/tomcat/webapps/manager:
    exists: false
    filetype: directory
    contains: []
group:
  tomcat:
    exists: true
    gid: 1000
  sshd:
    exists: false
package:
  curl:
    installed: true
  vim:
    installed: false
service:
  sshd:
    enabled: false
    running: false
user:
  sshd:
    exists: false
  tomcat:
    exists: true
    uid: 1000
    gid: 1000
    groups:
      - tomcat
    home: /home/tomcat
    shell: /bin/false

