version: '3.2'
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['initial_root_password'] = 'adminadmin'
        gitlab_rails['display_initial_root_password'] = true
    hostname: localhost
    container_name: gitlab
    restart: always
    #volumes:
    #  - /tmp/config:/etc/gitlab:Z
    #  - /tmp/logs:/var/log/gitlab:Z
    #  - /tmp/data:/var/opt/gitlab:Z \
    ports:
      - 443:443
      - 80:80