version: '3.2'
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['initial_root_password'] = 'adminadmin'
        gitlab_rails['display_initial_root_password'] = true
    hostname: localhost
    container_name: gitlab
    restart: always
    ports:
      - 443:443
      - 80:80
