apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tomcat8
spec:
  rules:
  - host: tomcat8.rko.com/
    http:
      paths:
      - path: /*
        pathType: Prefix
        backend:
          service:
            name: tomcat8
            port:
              number: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: tomcat8
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: tomcat8
---
apiVersion: apps/v1 # for kubectl versions >= 1.9.0 use apps/v1
kind: Deployment
metadata:
  name: tomcat8
  labels:
    app: tomcat8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat8
  template:
    metadata:
      labels:
        app: tomcat8
    spec:
      containers:
        - image: tomcat:8
          name: tomcat8
          ports:
            - containerPort: 8080
              name: http
